from typing import List, Dict
from datetime import datetime
from app.models.user import User
from app.schemas.meal import MealResponse, FoodItemResponse, NutritionInfoSchema
import random

class RecommendationEngine:
    """
    ML-powered recommendation engine for personalized meal plans.
    This is a simplified version - in production, you would use more sophisticated ML models.
    """
    
    # Sample food database (in production, this would be in a database)
    FOOD_DATABASE = {
        "breakfast": [
            {"name": "Oatmeal with berries", "calories": 300, "protein": 10, "carbs": 55, "fat": 5},
            {"name": "Greek yogurt with honey", "calories": 250, "protein": 20, "carbs": 30, "fat": 5},
            {"name": "Scrambled eggs with toast", "calories": 350, "protein": 20, "carbs": 30, "fat": 15},
            {"name": "Smoothie bowl", "calories": 400, "protein": 15, "carbs": 60, "fat": 10},
            {"name": "Avocado toast", "calories": 320, "protein": 12, "carbs": 40, "fat": 14},
        ],
        "lunch": [
            {"name": "Grilled chicken salad", "calories": 450, "protein": 40, "carbs": 20, "fat": 20},
            {"name": "Quinoa bowl with vegetables", "calories": 500, "protein": 18, "carbs": 70, "fat": 15},
            {"name": "Salmon with sweet potato", "calories": 550, "protein": 35, "carbs": 50, "fat": 22},
            {"name": "Turkey wrap", "calories": 400, "protein": 30, "carbs": 45, "fat": 12},
            {"name": "Lentil soup", "calories": 350, "protein": 20, "carbs": 55, "fat": 8},
        ],
        "dinner": [
            {"name": "Baked salmon with vegetables", "calories": 600, "protein": 45, "carbs": 30, "fat": 30},
            {"name": "Chicken stir-fry", "calories": 550, "protein": 40, "carbs": 50, "fat": 20},
            {"name": "Vegetable pasta", "calories": 500, "protein": 15, "carbs": 80, "fat": 12},
            {"name": "Beef and vegetable stew", "calories": 650, "protein": 50, "carbs": 40, "fat": 35},
            {"name": "Tofu curry", "calories": 450, "protein": 20, "carbs": 60, "fat": 15},
        ],
        "snack": [
            {"name": "Apple with almond butter", "calories": 200, "protein": 5, "carbs": 30, "fat": 8},
            {"name": "Greek yogurt", "calories": 150, "protein": 15, "carbs": 10, "fat": 5},
            {"name": "Mixed nuts", "calories": 250, "protein": 8, "carbs": 10, "fat": 20},
            {"name": "Protein shake", "calories": 180, "protein": 25, "carbs": 15, "fat": 3},
            {"name": "Hummus with vegetables", "calories": 220, "protein": 8, "carbs": 25, "fat": 10},
        ],
    }

    def recommend_meals(
        self,
        user: User,
        meal_type: str,
        target_calories: float
    ) -> List[MealResponse]:
        """
        Generate meal recommendations based on user profile and goals.
        """
        # Filter foods based on user preferences and restrictions
        available_foods = self._filter_foods_by_preferences(
            self.FOOD_DATABASE.get(meal_type, []),
            user
        )
        
        if not available_foods:
            # Fallback to all foods if no matches
            available_foods = self.FOOD_DATABASE.get(meal_type, [])
        
        # Select meals that match calorie target (with some flexibility)
        recommendations = []
        calorie_tolerance = target_calories * 0.2  # 20% tolerance
        
        for food in available_foods:
            if abs(food["calories"] - target_calories) <= calorie_tolerance:
                # Create meal response
                meal = MealResponse(
                    id=None,  # Will be generated by database
                    name=food["name"],
                    description=f"Recommended {meal_type} based on your profile",
                    meal_type=meal_type,
                    date=datetime.now(),
                    foods=[
                        FoodItemResponse(
                            id=None,
                            name=food["name"],
                            quantity=100.0,
                            unit="g",
                            nutrition=NutritionInfoSchema(
                                calories=food["calories"],
                                protein=food["protein"],
                                carbohydrates=food["carbs"],
                                fat=food["fat"],
                                fiber=5.0,  # Default value
                            )
                        )
                    ],
                    nutrition=NutritionInfoSchema(
                        calories=food["calories"],
                        protein=food["protein"],
                        carbohydrates=food["carbs"],
                        fat=food["fat"],
                        fiber=5.0,
                    )
                )
                recommendations.append(meal)
        
        # If no exact matches, return closest matches
        if not recommendations:
            available_foods.sort(key=lambda x: abs(x["calories"] - target_calories))
            top_foods = available_foods[:3]  # Top 3 closest matches
            
            for food in top_foods:
                meal = MealResponse(
                    id=None,
                    name=food["name"],
                    description=f"Recommended {meal_type} based on your profile",
                    meal_type=meal_type,
                    date=datetime.now(),
                    foods=[
                        FoodItemResponse(
                            id=None,
                            name=food["name"],
                            quantity=100.0,
                            unit="g",
                            nutrition=NutritionInfoSchema(
                                calories=food["calories"],
                                protein=food["protein"],
                                carbohydrates=food["carbs"],
                                fat=food["fat"],
                                fiber=5.0,
                            )
                        )
                    ],
                    nutrition=NutritionInfoSchema(
                        calories=food["calories"],
                        protein=food["protein"],
                        carbohydrates=food["carbs"],
                        fat=food["fat"],
                        fiber=5.0,
                    )
                )
                recommendations.append(meal)
        
        return recommendations[:5]  # Return top 5 recommendations

    def _filter_foods_by_preferences(self, foods: List[Dict], user: User) -> List[Dict]:
        """Filter foods based on user preferences, allergies, and dietary restrictions"""
        filtered = []
        
        for food in foods:
            # Check allergies (simplified - in production, check ingredient lists)
            if user.allergies:
                food_lower = food["name"].lower()
                for allergy in user.allergies:
                    if allergy.lower() in food_lower:
                        continue  # Skip this food
            
            # Check food preferences
            if user.food_preferences:
                food_lower = food["name"].lower()
                if "vegetarian" in user.food_preferences:
                    if any(meat in food_lower for meat in ["chicken", "beef", "turkey", "salmon", "meat"]):
                        continue
                if "vegan" in user.food_preferences:
                    if any(item in food_lower for item in ["egg", "yogurt", "milk", "cheese", "butter"]):
                        continue
            
            filtered.append(food)
        
        return filtered

